name: simple-openvpn-client-gui
base: core22
version: 1.0.2
summary: Just a simple OPENVPN client # 79 char long summary
description: |
  like https://snapcraft.io/simple-openvpn-client but with a gui available on http://loalhost:13131
  Place your OVPN certificate in the "/var/snap/simple-openvpn-client/common/" folder
  named "client.ovpn" then restart the app. The device will be connected at boot.
  the command is 
  sudo cp yourfile.ovpn  /var/snap/simple-openvpn-client/common/client.ovpn
  
  The app needs to have the right interfaces
  The command to connect an interface is:
  
  sudo snap connect <snap>:<plug interface>
  So basically:
  sudo snap connect simple-openvpn-client:network-control
  sudo snap connect simple-openvpn-client:firewall-control
  The apps starts at boot and connects the VPN server automatically.
confinement: strict
grade: stable

    
apps:

  vpn:  
    command: usr/sbin/openvpn
    plugs:
        - network
        - network-bind
        - network-control
        - firewall-control
  vpn-daemon:
    command: bin/clientrunner.wrapper
    daemon: simple
    restart-condition: always
    restart-delay: 5s
    plugs:
        - network
        - network-bind
        - network-control
        - firewall-control 
  flask-server: 
    command: bin/runserver.wrapper
    restart-condition: always  
    plugs:
      - network-control
      - network-observe
      - network
      - network-bind
      - desktop

    daemon: simple 
    

  desktop-launch: 
    command: bin/desktop-launch
    plugs:
      - network-control
      - network-observe
      - network
      - network-bind
      - desktop

  
    
parts:

  dependencies:
    plugin: python
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    python-packages: 
      - flask
      - requests
    source: .
    stage-packages:
       - openvpn
       - libatm-dev
       - curl
    build-packages:
      - python3-dev
      - python3-wheel
      - build-essential
      - python3-setuptools
  

  python-code:  
    source: ./Flask/
    plugin: dump
    organize:
      '*': bin/Flask/

  shscripts:  
    source: ./shscripts/
    plugin: dump
    organize:
      '*': bin/


